-- SQL Seed Data for Flames by the Indus
-- Generated based on src/lib/menuData.js

-- Clear existing data
TRUNCATE menu_items, categories, modifiers CASCADE;

-- Temporary table for category ID mapping during the script
CREATE TEMPORARY TABLE temp_cat (id UUID, name TEXT);

-- Insert Categories
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Karahi & Handi', 'Soup', 0) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Karahi & Handi' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Qorma & Curry', 'Soup', 1) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Qorma & Curry' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Nihari & Haleem', 'Soup', 2) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Nihari & Haleem' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('BBQ', 'Flame', 3) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'BBQ' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Rice', 'Utensils', 4) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Rice' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Tandoor', 'Cookie', 5) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Tandoor' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Chinese', 'Utensils', 6) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Chinese' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Street Food', 'Cookie', 7) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Street Food' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Desserts', 'Cookie', 8) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Desserts' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Beverages', 'GlassWater', 9) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Beverages' FROM inserted;
WITH inserted AS (INSERT INTO categories (name, icon, sort_order) VALUES ('Sides & Extras', 'Plus', 10) RETURNING id) INSERT INTO temp_cat (id, name) SELECT id, 'Sides & Extras' FROM inserted;

-- Insert Modifiers
INSERT INTO modifiers (key, name, type, options) VALUES ('spiciness', 'Spice Level', 'select', '[{"name":"Mild","price":0},{"name":"Medium","price":0},{"name":"Spicy","price":0},{"name":"Extra Spicy","price":0}]');
INSERT INTO modifiers (key, name, type, options) VALUES ('raita', 'Add-ons', 'multiselect', '[{"name":"Raita","price":50},{"name":"Salad","price":50}]');

-- Insert Menu Items
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Karahi & Handi' LIMIT 1), 'Chicken Karahi', 'Traditional Desi Chicken Karahi in wok.', 1200, 'Full', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop', '[{"name":"Half","price":700},{"name":"Full","price":1200}]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Karahi & Handi' LIMIT 1), 'Mutton Karahi', 'Tender Mutton Karahi with rich gravy.', 2200, 'Full', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop', '[{"name":"Half","price":1200},{"name":"Full","price":2200}]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Karahi & Handi' LIMIT 1), 'Chicken Handi', 'Creamy chicken handi with desi ghee.', 1400, NULL, 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?q=80&w=800&auto=format&fit=crop', '[{"name":"Half","price":800},{"name":"Full","price":1400}]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Karahi & Handi' LIMIT 1), 'Dumba Karahi', 'Premium lamb karahi with fat tails.', 2800, NULL, 'https://images.unsplash.com/photo-1545247181-516773cae754?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Karahi & Handi' LIMIT 1), 'Daal Makhni', 'Slow-cooked black lentils in creamy gravy.', 650, NULL, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Qorma & Curry' LIMIT 1), 'Chicken Qorma', 'Rich Mughlai style chicken qorma.', 900, NULL, 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Qorma & Curry' LIMIT 1), 'Mutton Qorma', 'Aromatic mutton in thick yogurt gravy.', 1400, NULL, 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Qorma & Curry' LIMIT 1), 'Chicken White Qorma', 'Creamy white chicken korma.', 950, NULL, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Qorma & Curry' LIMIT 1), 'Chicken Badami Qorma', 'Almond-rich chicken korma.', 1000, NULL, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Qorma & Curry' LIMIT 1), 'Chicken Jalfrezi', 'Spicy chicken with bell peppers.', 850, NULL, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Nihari & Haleem' LIMIT 1), 'Beef Nihari', 'Slow-cooked beef shank in rich spices.', 700, NULL, 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Nihari & Haleem' LIMIT 1), 'Mutton Nihari', 'Premium mutton nihari overnight stew.', 900, NULL, 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Nihari & Haleem' LIMIT 1), 'Beef Haleem', 'Hearty wheat and beef stew.', 550, NULL, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Nihari & Haleem' LIMIT 1), 'Mutton Haleem', 'Rich mutton haleem with garnish.', 700, NULL, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Chicken Tikka', 'Charcoal grilled chicken pieces.', 350, NULL, 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Seekh Kabab', 'Minced beef kababs with herbs.', 400, '4 pcs', 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Malai Boti', 'Creamy tender chicken cubes.', 450, NULL, 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Chapli Kabab', 'Peshawari flat beef kababs.', 450, '2 pcs', 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Chicken Chargha', 'Whole deep-fried marinated chicken.', 1200, NULL, 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'BBQ Platter', 'Mixed tikka, kabab, chops, boti.', 1500, NULL, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'BBQ' LIMIT 1), 'Lamb Chops', 'Juicy lamb chops marinated overnight.', 850, '4 pcs', 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['spiciness']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Rice' LIMIT 1), 'Chicken Biryani', 'Aromatic spicy chicken biryani.', 450, NULL, 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['raita']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Rice' LIMIT 1), 'Mutton Biryani', 'Saffron mutton biryani.', 650, NULL, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['raita']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Rice' LIMIT 1), 'Beef Biryani', 'Spicy beef biryani with potatoes.', 550, NULL, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop', '[]', ARRAY['raita']);
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Rice' LIMIT 1), 'Chicken Pulao', 'Fragrant rice with tender chicken.', 400, NULL, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Rice' LIMIT 1), 'Zarda', 'Sweet saffron rice with nuts.', 250, NULL, 'https://images.unsplash.com/photo-1567337710282-00832b415979?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Tandoor' LIMIT 1), 'Roghni Naan', 'Soft naan with sesame seeds.', 80, NULL, 'https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Tandoor' LIMIT 1), 'Garlic Naan', 'Naan with garlic butter.', 100, NULL, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Tandoor' LIMIT 1), 'Cheese Naan', 'Stuffed with melted cheese.', 150, NULL, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Tandoor' LIMIT 1), 'Tandoori Roti', 'Whole wheat tandoori bread.', 40, NULL, 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Tandoor' LIMIT 1), 'Paratha', 'Layered flaky bread.', 60, NULL, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Chinese' LIMIT 1), 'Chicken Chowmein', 'Stir-fried noodles with chicken.', 450, NULL, 'https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Chinese' LIMIT 1), 'Chicken Shashlik', 'Grilled skewers with bell peppers.', 550, NULL, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Chinese' LIMIT 1), 'Egg Fried Rice', 'Classic fried rice with eggs.', 350, NULL, 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Chinese' LIMIT 1), 'Hot & Sour Soup', 'Tangy and spicy soup.', 250, NULL, 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Street Food' LIMIT 1), 'Samosa', 'Crispy potato-filled pastries.', 80, '2 pcs', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Street Food' LIMIT 1), 'Samosa Chaat', 'Crushed samosa with chutneys.', 150, NULL, 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Street Food' LIMIT 1), 'Dahi Baray', 'Lentil dumplings in spiced yogurt.', 200, NULL, 'https://images.unsplash.com/photo-1572656631137-7935297eff55?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Street Food' LIMIT 1), 'Gol Gappay', 'Crispy puris with tangy water.', 150, NULL, 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Street Food' LIMIT 1), 'Pakora', 'Crispy fritters, assorted.', 120, NULL, 'https://images.unsplash.com/photo-1567337710282-00832b415979?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Desserts' LIMIT 1), 'Gulab Jamun', 'Hot milk dumplings in syrup.', 200, '4 pcs', 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Desserts' LIMIT 1), 'Kheer', 'Creamy rice pudding.', 250, NULL, 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Desserts' LIMIT 1), 'Gajar Ka Halwa', 'Warm carrot pudding with nuts.', 300, NULL, 'https://images.unsplash.com/photo-1567337710282-00832b415979?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Desserts' LIMIT 1), 'Ras Malai', 'Soft paneer in sweet milk.', 350, NULL, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Desserts' LIMIT 1), 'Shahi Tukray', 'Fried bread in sweetened milk.', 280, NULL, 'https://images.unsplash.com/photo-1551326844-4df70f78d0e9?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Doodh Patti', 'Strong Pakistani milk tea.', 100, NULL, 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Kashmiri Chai', 'Pink tea with nuts.', 180, NULL, 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Lassi (Sweet)', 'Creamy yogurt drink.', 180, NULL, 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Fresh Lime', 'Refreshing lime soda.', 150, NULL, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Soft Drink', 'Chilled Pepsi, Sprite, 7Up.', 120, NULL, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Beverages' LIMIT 1), 'Mineral Water', '500ml bottled water.', 80, NULL, 'https://images.unsplash.com/photo-1560023907-5f339617ea30?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Sides & Extras' LIMIT 1), 'Raita', 'Yogurt with cucumber & mint.', 100, NULL, 'https://images.unsplash.com/photo-1572656631137-7935297eff55?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Sides & Extras' LIMIT 1), 'Green Salad', 'Fresh garden salad.', 150, NULL, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Sides & Extras' LIMIT 1), 'Russian Salad', 'Creamy mayo vegetable salad.', 200, NULL, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Sides & Extras' LIMIT 1), 'French Fries', 'Crispy golden fries.', 250, NULL, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800&auto=format&fit=crop', '[]', '{}');
INSERT INTO menu_items (category_id, name, description, price, unit, image, variants, modifiers) VALUES ((SELECT id FROM temp_cat WHERE name = 'Sides & Extras' LIMIT 1), 'Achar (Pickle)', 'Spicy mixed pickle.', 80, NULL, 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?q=80&w=800&auto=format&fit=crop', '[]', '{}');

DROP TABLE temp_cat;